version: "3.8"

services:
  bagisto-dev:
    image: bagisto-custom:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
      - "2222:22"
    volumes:
      - ./workspace:/var/www/html
    networks:
      - bagisto_net

  mysql_bagisto:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: bagisto
      MYSQL_USER: bagisto
      MYSQL_PASSWORD: bagisto123
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - bagisto_net

networks:
  bagisto_net:
